gesture_decision:
  ros__parameters:
    mode: "robot"
    debounce_frames: 2
    cooldown_sec: 1.5
    idle_timeout_sec: 2.0
    publish_every_frame: false
    min_confidence: 0.60
    start_gesture: "5"
    space_gesture: "3"
    end_gesture: "7"
    delete_gesture: "8"
    commit_gesture: "5"
    gesture_labels:    ["0","a","s","m","n","o","e","t"]
    gesture_actions:  ["STOP","STOP","STOP","STOP","STOP","STOP","STOP","STOP"]
    gesture_priority: [true,true,true,true,true,true,true,true]
    combo_labels:     ["5+1","5+d","5+2","5+v","5+u","5+3","5+4","5+b","3+1","3+d","3+2","3+v","3+u"]
    combo_actions:    ["MOVE_FORWARD","MOVE_FORWARD","MOVE_BACK","MOVE_BACK","MOVE_BACK","TURN_LEFT","TURN_RIGHT","TURN_RIGHT","LOOK_UP","LOOK_UP","LOOK_DOWN","LOOK_DOWN","LOOK_DOWN"]
    combo_priority:   [false,false,false,false,false,false,false,false,false,false,false,false,false]

